apiVersion: v1
kind: Service
metadata:
  name: papyrus-hello
  namespace: hownee
  labels:
    app: papyrus-hello
    type: papyrus-module
spec:
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: papyrus-hello